### ISSUE TITLE
esp8266 512kb

### ISSUE THREAD

**Issue by Hapod** [renat2985/esp8266-Radio#2]
Подскажите пожалуйста получится ли использовать esp8266 с объемом памяти 512 kb для этого проекта?

**Comment by renat2985** [comment]
Скорее всего нет.

**Comment by Hapod** [comment]
Попробовал залить прошивку в esp8266 с объемом памяти 512 kb. Все работает без проблем, залилась прошивка на ура. 
Вопрос web сервер работает только при начальной настройке или после подключения к точке доступа тоже должен работать?

**Comment by renat2985** [comment]
После подключения к роутеру web сервер не запускается. esp8266 тяжело справляться с потоком трансляции, если включить web сервер будет совсем запинаться.

**Comment by Hapod** [comment]
Спасибо за информацию.

**Comment by Serzh20000** [comment]
Вы писали в комментариях

Проще и дешевле будет сделать установку нужной радиостанции при первом старте, когда подключаем устройство к Роутеру. Можно сформировать нужный список радиостанции. А в будущем переключать их стационарной кнопкой по кругу, но не через веб интерфейс.﻿

 я с этим на все сто согласен 3-5 радиостанций больше и не надо, не надо никаких дисплеев, ни каких стерео да и ваще ни каких примочек одна кнопка и все. и еще бы через 10-15 минут не заикалось радио совсем супер было бы!
