### ISSUE TITLE
MP3 is done

### ISSUE THREAD

**Issue by DooDip** [renat2985/esp8266-Radio#5]
Hello! I'm trying to get this to work and I've gotten it to compile. I've loaded it on nodemcu esp-12e but the terminal just says Mp3 is done over and over. I dont hear any sound through the speaker. Does the speaker hook up to TX and Ground on the esp-12e? I've tested the MP3 link in the radio.ino and it works on the computer.

**Comment by musicb0x** [comment]
Which one should be compiled or upload? The "Radio.ino" or the "esp8266-Radio.ino"
Can you send/post the single .ino file please.
