### ISSUE TITLE
Добавление ссылок на радио.

### ISSUE THREAD

**Issue by mishailovic** [renat2985/esp8266-Radio#6]
Очень интересует изменение радио, подскажите пожалуйста как это сделать, а то джаз уже надоел, хочу dfm или что то ещё!

**Comment by pav18** [comment]
Приветствую. Говорили вроде, что можно будет со временем добавлять свое радио. Движется что-нибудь в этом направлении? Проект отличный, спасибо.

**Comment by mishailovich** [comment]
Ага, тот же вопрос!
